version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./debug.log:/app/debug.log
    expose:
      - 80
    environment:
      # environment defined in .env file
      - DJANGO_KEY=${DJANGO_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    restart: always

networks:
  default:
    external:
      name: nginx-proxy