version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./debug.log:/app/debug.log
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=staging.agimpel.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=staging.agimpel.com
    restart: always

networks:
  default:
    external:
      name: nginx-proxy