version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./debug.log:/app/debug.log
    expose:
      - 80
    # environment defined in .env file
    restart: always

networks:
  default:
    external:
      name: nginx-proxy